<?php

namespace AppBundle\Repository;

/**
 * CrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudRepository extends \Doctrine\ORM\EntityRepository
{
}
